### ISSUE TITLE
char int values referenced are actually hex references

### ISSUE THREAD

**Issue by hwbrill** [davidgatti/How-to-Understand-Sockets-Using-IoT#3]
Hello David, by the way... Your repo is awesome!  Please refer to http://www.ascii-code.com/....
You're pretty close in your readme.md docs but are not int but hex references.  The rational for the ASCII standard was put in effect to drive 7 segment numeric displays where the first four bits represent the control bits.  If you refer to the link, the decimal for the char '0' is dec 48 (hex 30) and char '9' is dec 57 (hex 39).

**Comment by davidgatti** [comment]
OMG, sorry @hwbrill I missed your Issue :( to many emails form GitHub I guess. I'm really sorry for that. 

1. I'm really happy that you like my article :) 
2. Could you tell me a bit more what I didn't get, and how can I make the article better? I'm not sure I follow what are you trying to say :)

**Comment by davidgatti** [comment]
@hwbrill OO... I think I understand now. After checking your PR now I was ablate put it all together. Well in my example I'm not using the integers as ASCII reference. But just a regular integers, as numbers - nothing more.

If the confusion comes from a sentence before, please let me know so I can fix it.
